[workspace]
members = [
    "frame/attestor",
    "frame/bridge",
    "frame/bridgetransfer",
    "frame/geode",
    "frame/liveness",
    "frame/transfer",
    "frame/witness",
    "frame/vesting",
    "frame/economics",
    "primitives",
    "node-template/node",
    "node-template/pallets/template",
    "node-template/runtime",
]

[profile.release]
# Automata runtime requires unwinding.
panic = "unwind"

