[workspace]
members = [
    "frame/attestor",
    "frame/bridge",
    "frame/bridgetransfer",
    "frame/geode",
    "frame/liveness",
    "frame/transfer",
    "frame/vesting",
    "primitives"
]

[profile.release]
# Automata runtime requires unwinding.
panic = "unwind"